server:
  port: 8083
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: family-service

  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR}:8848
      config:
        group: DEFAULT_GROUP
        file-extension: yaml
        encode: UTF-8
        namespace: ${NACOS_NAMESPACE}
      discovery:
        namespace: ${NACOS_NAMESPACE}
  config:
    import:
      - file:.env[.properties]
      - nacos:common-spring.yaml
      - nacos:common-logs.yaml
      - nacos:common-mybatis.yaml
      - nacos:family-service-dubbo.yaml

sh:
  jdbc:
    host: ${MYSQL_SERVER_ADDR}
    password: ${MYSQL_ROOT_PASSWORD}
    database: sh_family
  nacos:
    server-addr: ${NACOS_SERVER_ADDR}
    namespace: ${NACOS_NAMESPACE}

logging:
  level:
    asia.sweethome: debug

