server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR}:8848
      config:
        group: DEFAULT_GROUP
        file-extension: yaml
        encode: UTF-8
        namespace: ${NACOS_NAMESPACE}
      discovery:
        namespace: ${NACOS_NAMESPACE}
    gateway:
      server:
        webflux:
          routes:
            - id: auth-route
              uri: lb://auth-service
              predicates:
                - Path=/v1/auth/**
            - id: user-route
              uri: lb://user-service
              predicates:
                - Path=/v1/users/**
            - id: family-route
              uri: lb://family-service
              predicates:
                - Path=/v1/families/**
            - id: chat-route
              uri: lb://chat-service
              predicates:
                - Path=/v1/conversations/**
            - id: ws-route
              uri: lb:ws://chat-service
              predicates:
                - Path=/v1/ws
            - id: location-route
              uri: lb://location-service
              predicates:
                - Path=/v1/location/**
          discovery:
            locator:
              enabled: false


  config:
    import:
      - file:.env[.properties]
      - nacos:common-spring.yaml
      - nacos:common-logs.yaml

jwt:
  public-key: ${JWT_PUBLIC_KEY}

logging:
  level:
    asia.sweethome: debug

