server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: user-service

  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR}:8848
      config:
        group: DEFAULT_GROUP
        file-extension: yaml
        namespace: ${NACOS_NAMESPACE}
      discovery:
        namespace: ${NACOS_NAMESPACE}
  config:
    import:
      - optional:file:.env[.properties]
      - optional:nacos:common-spring.yaml
      - optional:nacos:common-logs.yaml
      - optional:nacos:common-mybatis.yaml
      - optional:nacos:common-dubbo.yaml

sh:
  jdbc:
    host: ${MYSQL_SERVER_ADDR}
    password: ${MYSQL_ROOT_PASSWORD}
    database: sh_user
  nacos:
    server-addr: ${NACOS_SERVER_ADDR}

logging:
  level:
    asia.sweethome: debug

